### ISSUE TITLE
Docstring: return value of (manifold.deferred/finally x f)

### ISSUE THREAD

**Issue by pbwolf** [clj-commons/manifold#101]
The doc string for `manifold.deferred/finally` says in part, "An equivalent of the finally clause".  A more precise description of its return value would be helpful:  "Returns an error deferred wrapping the exception thrown by f if any, otherwise returns x."  The additional clarity would be warranted because `manifold.deferred/chain` and `manifold.deferred/catch` treat alike either an exception they catch or an error-deferred they receive, but `manifold.deferred/finally` does not.  The final function _must_ throw if it wants to influence the result of a chain.  (The `manifold.deferred/finally` doc string characterizes the no-arg function as "side-effecting", but it is a bit subtle to overcome what seems to be Manifold's general rule about exceptions.)

**Comment by figurantpp** [comment]
Would a PR that covers this be welcome? I find this documentation change fit for this function, since the return value for `finally` is  not exactly obvious nor documented.

**Comment by KingMob** [comment]
@figurantpp Sure, a PR is welcome, but flip the order around to say "Returns x unless a Throwable is thrown in f, in which case it returns an error-deferred."

**Comment by figurantpp** [comment]
I believe #222 closes this issue

**Comment by KingMob** [comment]
Closed by #222
