### ISSUE TITLE
Custom buffers? - sliding and dropping streams

### ISSUE THREAD

**Issue by vspinu** [clj-commons/manifold#129]
Hi,

How can I build custom buffers akin to `droping-buffer`, `sliding-bufer`, `promice-buffer` in `core.async`?

Thanks!

**Comment by ztellman** [comment]
There's not a perfect analogue to this in Manifold, but you can use `connect-via-buffer` to do something similar.  There are multiple examples of this in the `manifold.stream` namespace.

**Comment by vspinu** [comment]
I don't see any mentions of `connect-via-buffer` anywhere. Do you mean `connect-via` for connections through callbacks?

**Comment by ztellman** [comment]
Sorry, I meant `connect-via-proxy`.  But `connect-via` could also be used by itself.

**Comment by rschmukler** [comment]
In case anyone finds themselves in need:

```
(defn dropping-buffer
  "Wraps the `source` buffer with a stream with buffer size `n` which will drop items.

  If no source is specified, creates a new stream with the provided capacity."
  ([n]
   (let [in  (s/stream)
         out (dropping-buffer n in)]
     (s/splice in out)))
  ([n source]
   (let [result (s/stream n)]
     (s/connect-via
      source
      (fn [val]
        (println val)
        (let-flow [_ (s/try-put! result val 0)]
          true))
      result)
     result)))

(defn sliding-buffer
  "Wraps the `source` stream with a buffer of size `n` which will drop the oldest
  items when capacity is hit.

  If no source is specified, creates a new stream with the provided capacity. "
  ([n]
   (let [in  (s/stream)
         out (sliding-buffer n in)]
     (s/splice in out)))
  ([n source]
   (let [result (s/stream n)]
     (s/connect-via
      source
      (fn [val]
        (d/loop []
          (d/chain
           (s/try-put! result val 0)
           (fn [put-okay?]
             (if put-okay?
               true
               (d/chain (s/take! result) (fn [_] (d/recur))))))))
      result)
     result)))
```

**Comment by den1k** [comment]
@rschmukler do you have the impls for `dropping-buffer` and `sliding-buffer`?

**Comment by rschmukler** [comment]
@den1k sorry there was an error in the comment. I've updated the comment above with the latest code. the `dropping-buffer` and `sliding-buffer` were just misnamed recursive functions. Additionally I later added code that handles the wrapped stream closing (which would cause an infinite recursion) - make sure you grab the updated code from the comment above.

:beers:

**Comment by den1k** [comment]
perfect! cheers @rschmukler 🍻

**Comment by KingMob** [comment]
Closing. 

@rschmukler, you're welcome to submit a PR to add these fns.
