### ISSUE TITLE
ProcessPipeInputStream

### ISSUE THREAD

**Issue by dpom** [clj-commons/manifold#199]
Is it possible to convert (or transfer bytes) from a java.lang.ProcessImpl$ProcessPipeInputStream  to a manifold stream?

**Comment by KingMob** [comment]
Hi @dpom ! For future reference, the #aleph channel on the Clojurians Slack is the best place to get answers for questions like this.

In this case, you want to pull in `byte-streams` for the conversion. E.g.:

```clojure
(require '[byte-streams :as bs])
(bs/convert your-process-input-pipe-stream (bs/stream-of bytes) {:chunk-size 4096}) 
```

will give you a Manifold stream that returns byte arrays in 4096-byte chunks.

There's other built-in conversion options, and you can define your own, too. Hope this helps.

**Comment by dpom** [comment]
Thanks @KingMob for the information and the solution
