### ISSUE TITLE
d/alt docstring wrong?

### ISSUE THREAD

**Issue by DerGuteMoritz** [clj-commons/manifold#205]
The docstring for `d/alt` says:

> Values appearing earlier in the input are preferred.

I understand this to mean that the given arguments are checked from left to right (as in `core.async/alt!` with `:priority true`). However, the implementation actually randomizes the order. From https://github.com/clj-commons/manifold/pull/102 I gather that this was changed during review but the docstring wasn't adjusted accordingly.

**Comment by KingMob** [comment]
Good catch. Feel free to submit a PR, otherwise, I'll fix it in the next couple weeks.
