### ISSUE TITLE
stream documentation has some errors 

### ISSUE THREAD

**Issue by henryw374** [clj-commons/manifold#227]
In this line: https://github.com/clj-commons/manifold/blob/master/doc/stream.md?plain=1#L121 

it refers to a function `(permanent-stream)` which doesn't seem to exist - just `:permanent? true` would be correct afaict. 

The other issue is where it says ` if everything downstream of s is closed, s will also be closed` 

but, if after doing the following, I close `a`, then `s` is not closed. 

```
> (def s (s/stream))
#'s
> (def a (s/map inc s))
```

**Comment by KingMob** [comment]
Good catch on the `permanent-stream` reference. I'll update the docs.

So, if all downstreams are closed, the upstream _will_ be closed, just not immediately. One thing Manifold doesn't have great support for is bidirectional connections in the streams. This supports using a lot of data structures that aren't Manifold streams in Manifold, but the consequence is that the most reliable way to determine if a downstream is closed is to attempt to `put!` to it, and see if that fails.

The way Manifold handles closing upstreams in this situation is to check on `put` failures if there are no downstreams left, and if so, close the upstream.

E.g: 
```clojure
(let [s (s/stream)
      a (s/map inc s)
      b (s/map inc s)]
  (println "s closed at start:" (s/closed? s))

  (s/close! a)
  (s/close! b)
  
  (println "s closed immediately after closing downstreams:" (s/closed? s))

  (let [put-attempt @(s/put! s 42)]
    (println "s closed after a put attempt:" (s/closed? s))))
=>
s closed at start: false
s closed immediately after closing downstreams: false
s closed after a put attempt: true
```

It's been on the to-do list for a while to add weak references to upstreams to make this easier, but it will never work for some downstreams. As one example, the downstreams created by the `consume*` fns can _only_ be closed when a put is attempted and they return false; there's no concept of "closing" a function. (We could expose the underlying `Callback` stream, but that will add a lot of confusion for little benefit, and break with the existing APIs.)

You're not the first person to ask this, though, so I'll add a note in the docs about this, too.

**Comment by henryw374** [comment]
Thanks, I understand now. https://github.com/clj-commons/manifold/pull/228 looks good!
